default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default
  channel_prefix: egbe_link_hub_development

test:
  <<: *default
  channel_prefix: egbe_link_hub_test

production:
  <<: *default
  channel_prefix: egbe_link_hub_production
